# Workflow for build and test using gradle and cucumber

name: CI with Java, Gradle and Cucumber

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Setup java
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # Run build using Gradle
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: build/libs
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: build/libs

    # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

    # Run tests using Gradle 
      - name: Test with Gradle
        run: ./gradlew test --rerun-tasks --info
